beamlet_star_node:
  ros__parameters:

    rows: 8
    cols: 8

    grid: [
      0,0,0,0,1,1,1,1,
      0,0,0,0,1,1,1,1,
      1,1,0,0,1,1,1,1,
      1,1,0,0,1,1,1,1,
      0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,1,0,
      0,0,0,0,1,1,0,0,
      0,0,0,0,1,1,0,0
    ]

    smax: 3
    alpha: 0.0
